version: '3'
services:
    express:
        build: 
            context: . 
            dockerfile: Dockerfile
        image: freewheel_image:local
        container_name: freewheel_container01
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./:/freewheel
            - /freewheel/node_modules